# This yaml brings up node agent as a DaemonSet.
# A detailed tutorial will be added soon.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nodeagent
spec:
  template:
    metadata:
      labels:
        app: nodeagent
        version: v1
    spec:
      containers:
      - name: nodeagent
        image: "docker.io/quanlin/node-agent-k8s:180712-1102"
        imagePullPolicy: IfNotPresent
