# This yaml brings up node agent as a DaemonSet.
# A detailed tutorial will be added soon.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nodeagent
spec:
  template:
    metadata:
      labels:
        app: nodeagent
        version: v1
    spec:
      containers:
      - name: nodeagent
        image: "docker.io/quanlin/nodeagent:180725-1145"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/run/sds
          name: sdsudspath
      volumes:
      - name: sdsudspath
        hostPath:
          path: /var/run/sds