FROM istionightly/base_debug
ARG proxy_version
ARG istio_version

# Install Envoy.
ADD envoy /usr/local/bin/envoy

# Environment variables indicating this proxy's version/capabilities as opaque string
ENV ISTIO_META_ISTIO_PROXY_VERSION "1.1.0"
# Environment variable indicating the exact proxy sha - for debugging or version-specific configs 
ENV ISTIO_META_ISTIO_PROXY_SHA $proxy_version
# Environment variable indicating the exact build, for debugging
ENV ISTIO_META_ISTIO_VERSION $istio_version

ADD pilot-agent /usr/local/bin/pilot-agent

ADD envoy_pilot.yaml.tmpl /etc/istio/proxy/envoy_pilot.yaml.tmpl
ADD envoy_policy.yaml.tmpl /etc/istio/proxy/envoy_policy.yaml.tmpl
ADD envoy_telemetry.yaml.tmpl /etc/istio/proxy/envoy_telemetry.yaml.tmpl
ADD istio-iptables.sh /usr/local/bin/istio-iptables.sh
ADD ca-root-cert.pem /etc/istio/certs/ca-root-cert.pem

COPY envoy_bootstrap_v2.json /var/lib/istio/envoy/envoy_bootstrap_tmpl.json

RUN chmod 755 /usr/local/bin/envoy /usr/local/bin/pilot-agent

# Sudoers used to allow tcpdump and other debug utilities.
RUN useradd -m --uid 1337 istio-proxy && \
    echo "istio-proxy ALL=NOPASSWD: ALL" >> /etc/sudoers && \
    chown -R istio-proxy /var/lib/istio

RUN mkdir -p /var/run/secrets/tokens && \
    chown -R istio-proxy /var/run/secrets/tokens

RUN mkdir -p /var/run/secrets/tokentest && \
    chown -R istio-proxy /var/run/secrets/tokentest && \
    echo "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJhdWQiOlsidmF1bHQiXSwiZXhwIjoxNTM4Njk4ODA1LCJpYXQiOjE1Mzg2OTE2MDUsImlzcyI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9na2Utb2lkYy9iZWUwNjBlNGEzZWQ2NTMyYjg0YzRjYjI5MTY0MzcxNjUwNGExNWY5NGMwNzBjMDE3OGU5NzdjNjU1MzUwNjZkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0IiwicG9kIjp7Im5hbWUiOiJoZWxsb3BvZCIsInVpZCI6ImE1MmVjNzk1LWM4MjMtMTFlOC04ZGZjLTQyMDEwYTgwMDAwNyJ9LCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiamVua2lucyIsInVpZCI6ImE1MWZjYjNmLWM4MjMtMTFlOC04ZGZjLTQyMDEwYTgwMDAwNyJ9fSwibmJmIjoxNTM4NjkxNjA1LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpqZW5raW5zIn0.bL-Awy10Bg8i4AEqvv8z-A2CnA9ypjKiKBHIeyayLn1C3btplN72agY20eJq0vz57bVpfp76ISSVyfTK0O4txfbwqW1wz_-uPI9FuPy0iLlE7B_pY_io2vdhFeKWiaYzsomw_fu0NAI1w5u5Uwr13Jue3jAIDlKwS7Tkcr3MV73-FWp4mKJIoCXaq58BGdEybK3rootroot@helc" >> /var/run/secrets/tokentest/vault-token

# The pilot-agent will bootstrap Envoy.
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
